using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HotelSystem.Infrastructure.WPF.Attributes
{
    /// <summary>
    /// An attribute used to signal that the property which this attribute
    /// is assigned to does not get autogenerated in CustomDataGrid
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public sealed class DoNotAutoGenerateAttribute : Attribute
    {
    }
}
