// <auto-generated />
namespace HotelSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FirstCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201811101950560_FirstCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
